### ISSUE TITLE
Setup question

### ISSUE THREAD

**Issue by ErikLambrechts** [frank-zago/ch341-i2c-spi-gpio#1]
Forgive me my lacking understanding of Linux modules. I'm stuck setting up this project. I don't understand the next instruction properly.
```
This will create ch341-buses.ko, which can the be insmod'ed.
```
Compile the code works flawlessly and results in the aforementioned `ch341-buses.ko` file. Using `insmod` is not clear to me.
As far as I understand, I'm supposed to run 
```
sudo insmod ch341-buses.ko
```
But this results in the following error,
```
insmod: ERROR: could not insert module ch341-buses.ko: Invalid module format
```
Thanks in advance.

**Comment by frank-zago** [comment]
Look at the output of `dmesg`. There might be some error there too.
