### ISSUE TITLE
 BUG: unable to handle page fault for address: ffffffffc300b1e8

### ISSUE THREAD

**Issue by sacarlson** [frank-zago/ch341-i2c-spi-gpio#25]
I compiled the code sudo make install  and followed the instructions in your notes
I made sure I have installed the headers for the kernel I am running that is 5.15.0-83-generic on linux mint.
I did try reboot and uninstall reinstall but same error when I install the device that is it's that USB_LoRa_adapter-PINE64_RFM90.
I see this error in dmeg :
[  362.668007] BUG: unable to handle page fault for address: ffffffffc300b1e8
[  362.668010] #PF: supervisor write access in kernel mode
[  362.668011] #PF: error_code(0x0003) - permissions violation
[  362.668013] PGD 1ec415067 P4D 1ec415067 PUD 1ec417067 PMD 11cb79067 PTE 8000000108ea3061
[  362.668017] Oops: 0003 [#1] SMP PTI
[  362.668019] CPU: 3 PID: 4995 Comm: systemd-udevd Tainted: P           OE     5.15.0-83-generic #92-Ubuntu
for full error see link
[driver_bug.txt](https://github.com/frank-zago/ch341-i2c-spi-gpio/files/13847933/driver_bug.txt)

after I upgraded kernel to 6.1.0-1027-oem
recompiled sudo make install.   seems ok now.  no dmesg errors seen.  I haven't fully tested the device with it yet but might be ok.

**Comment by frank-zago** [comment]
I haven't had time to look at that. There was a recent change to add support for older kernels. Maybe something is missing there?
