### ISSUE TITLE
Fix page-fault in kernel 5.15

### ISSUE THREAD

**Issue by iotmaker33** [frank-zago/ch341-i2c-spi-gpio#33]
Hi,

I make a patch to fix the page-fault bug in kernel 5.15 (Ubuntu 22.04 LTS)
Could you help to review this and help to integrate this patch ?

Thanks.
[gpio.patch.gz](https://github.com/frank-zago/ch341-i2c-spi-gpio/files/14590143/gpio.patch.gz)

**Comment by iotmaker33** [comment]
Hi,

I found you remove IRQCHIP_IMMUTABLE macro too. There is no IRQCHIP_IMMUTABLE before 5.19. Could you help to add the following line ?

#define IRQCHIP_IMMUTABLE 0

thanks.

**Comment by frank-zago** [comment]
Sorry about that. Not sure how that happened. It's back now.

**Comment by iotmaker33** [comment]
It works well now. Thanks for your hard work
