### ISSUE TITLE
spi-ch341.c : error with kernel 6.8.0

### ISSUE THREAD

**Issue by Tian-HP** [frank-zago/ch341-i2c-spi-gpio#37]
Linux version 6.8.0
spi-ch341.c:196:54: error: array subscript is not an integer
spi-ch341.c:515:25: error: implicit declaration of function ‘gpiochip_find’; did you mean ‘gpiochip_add’?

**Comment by frank-zago** [comment]
I pushed an update to fix that.

**Comment by Tian-HP** [comment]
I got it.
